### ISSUE TITLE
Eco temperature templating?

### ISSUE THREAD

**Issue by Johnymalina** [KartoffelToby/better-thermostat-ui-card#124]
Hi iam not able to change eco temperature settings using slider i wanted to make change eco temperature more interactive using HA helper to be able to set eco temperature but template is not working in this card. Is there any chance to call a script pressing the eco button or any other way to change eco temperatute without using yaml everytime?
```
type: custom:better-thermostat-ui-card
entity: climate.living_room_heating
eco_temperature: '{{ states(''input_number.eco_temperature'') | int}}'
```

**Comment by duedipicche** [comment]
Same problem:
```
eco_temperature: 
                  value_template: "{{ state_attr('climate.myClimate Entity', 'current_temperature') | float(99.0) }}"
```
don't work
and:
`eco_temperature:  "{{ state_attr('climate..myClimate Entity', 'current_temperature') | float(99.0) }}"`
don't work.
in booth case the response is:
**Invocation of better_thermostat/set_temp_target_temperature service failed. expected float for dictionary value @ data['temperature']**
thanks

**Comment by nyphis** [comment]
Same problem here. I want to give this a push.

I use different away temperatures over the year and I use an entity with the target Eco temp.

The templating works when I call the service in an automation ... @duedipicche
```YAML
action: better_thermostat.set_temp_target_temperature
target:
  entity_id: climate.bt_thermostat
data:
  temperature: "{{ states('number.thermostat_kinderzimmer_away_preset_temperature') | float }}"
``` 

But the BT card does not accept any templates. Trying
```YAML
type: custom:better-thermostat-ui-card
entity: climate.bt_thermostat
eco_temperature: "{{ states('number.thermostat_kinderzimmer_away_preset_temperature') | float }}"
```
fails with `At path: eco_temperature -- Expected a number, but received: "{{ states('number.thermostat_kinderzimmer1_away_preset_temperature') | float }}"` (I also tried using to provide an integer `| int` but neither works).
