### ISSUE TITLE
Climates low and high temperature is swichted

### ISSUE THREAD

**Issue by michaelhenningersrb** [KartoffelToby/better-thermostat-ui-card#140]
Hi,

I have configured a mqtt climate manually. Here is my configuration:

```yml
- name: Heizung
  unique_id: central_heating
  max_temp: 30
  min_temp: 10
  modes:
    - "off"
    - "auto"
    - "heat"

  temperature_command_topic: "heatpump/room-settemp-comfort/write"
  temperature_state_topic: "heatpump/room-settemp-comfort/value"
  current_temperature_topic: "homeassistant/sensor/temperatur_esszimmer/state"
  mode_state_topic: "heatpump/progswitch/value"

  mode_command_topic: "heatpump/progswitch/write"
  temperature_high_state_topic: "heatpump/room-settemp-comfort/value"
  temperature_high_state_template: "{{ value_json | float }}"
  temperature_high_command_topic: "heatpump/room-settemp-comfort/write"

  temperature_low_state_topic: "heatpump/room-settemp-eco/value"
  temperature_low_state_template: "{{ value_json | float }}"
  temperature_low_command_topic: "heatpump/room-settemp-eco/write"

```

In general this configuration works, also the states are correctly filled:

![image](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/18479766/c8f7410b-be4a-447a-8364-f62477f2c672)

Please note `target_temp_high: 22.9` and `target_temp_low: 21`

If I add the `[better-thermostat-ui-card](https://github.com/KartoffelToby/better-thermostat-ui-card)` to my dashboard, it looks like this:
![image](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/18479766/f892e32d-a033-4ea0-8fc8-4522d220366d)

It looks like the low and the high temperature is switched. Is this the correct behaviour?
