### ISSUE TITLE
Cooling colour set incorrectly

### ISSUE THREAD

**Issue by keni8em** [KartoffelToby/better-thermostat-ui-card#141]
After setting up a smart mini-fridge, I noticed that the better-thermostat-ui-card is displaying the wrong colour for the cooling hvac mode.
On inspection of "better-thermostat-ui-card.js" the problem lies in the following code:
```
.cool {
        --mode-color: var(--label-badge-red);
```
I suggest changing this code to `"--label-badge-blue"`
See the attached image showing that the cooling thermostat is displaying red rather than blue.

![Screenshot from 2023-11-22 02:14:43](https://github.com/KartoffelToby/better-thermostat-ui-card/assets/30601590/f48131ad-9d04-4748-97da-d9d009ea84df)

**Comment by laborek** [comment]
up!

**Comment by laborek** [comment]
@keni8em did u change this by yourself ?

**Comment by Duke-Box** [comment]
Why is the HVAC mode Heat now showing Blue? Has someone hacked this?

**Comment by keni8em** [comment]
Not that setting. What I did was use my browser tools to identify the css setting for the thermostat. I was therefore able to see that both the heating HVAC and the cooling HVAC are using the same control variable, there resulting in the cooling image appearing as red not blue. Regards,Kenneth. On 2 Dec 2023, at 08:47, laborek ***@***.***> wrote:﻿
@keni8em did u change this by yourself ?

**Comment by macbih** [comment]
Is there any fix for this issue yet?

I am using a `generic_thermostat` for a RPI Cooling Fan Controller and I wonder why the color is also red instead of blue. Its one and only function is to cool the Pi with a fan. This is my code:

```
climate:

  # https://community.home-assistant.io/t/rpi4-fan-control/610597

  - platform: generic_thermostat
    name: RPI Cooling Fan Controller
    unique_id: rpi_cooling_fan_controller
    heater: switch.rpi_cooling_fan
    target_sensor: sensor.system_monitor_processor_temperature
    min_temp: 40
    max_temp: 80
    ac_mode: true
    target_temp: 50
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 120
    keep_alive:
      minutes: 5
    initial_hvac_mode: "cool"
```

Thank you!
