### ISSUE TITLE
Option to disable circular slider touches. 

### ISSUE THREAD

**Issue by zorvalth** [KartoffelToby/better-thermostat-ui-card#191]
When I open my dashboard on mobile and scrolling through if i accidently click somewhere on the circular slider it changes the temp and i dont notice it. Can it be implemented an option to disable the touch option of the circular slider, so it can be only adjusted through the + and - buttons?

**Comment by isiorg** [comment]
I have the same problem. All time if I scroll, the temperature change.

**Comment by lucasop** [comment]
I disabled the slide with HACS card-mod

``` javascrips
type: custom:better-thermostat-ui-card
entity: climate.thermostato_soggiorno
eco_temperature: 19
card_mod:
  style:
    .: |
      .more-info {
        width: 0;
      }
    bt-ha-control-circular-slider$: |
      g#interaction {
        display: none;
      }
```

**Comment by tOOmki** [comment]
I don't want to completely disable regulation. Add some kind of lock to change the setting.

**Comment by dimex2015** [comment]
Can you tell me how to disable the slider?

```
card_mod:
  style:
    .: |
      .more-info {
        width: 0;
      }
    bt-ha-control-circular-slider$: |
      g#interaction {
        display: none;
      }
```

<img width="955" alt="Image" src="https://github.com/user-attachments/assets/69a0fe13-a23c-4040-93f2-4ece27981ce2" />

**Comment by giomf** [comment]
Im also interested in this.
I was not able to achieve this with card-mod.
A simple option like we already have for the other options would be great.

**Comment by fleshinachair** [comment]
I'd also love this to be added. I keep accidentally changing my settings when scrolling

**Comment by isiorg** [comment]
Me to!!!!

**Comment by ThomDietrich** [comment]
Please add this feature ❤️ 

In the meantime, the workaround does it for me.

```yaml
type: custom:better-thermostat-ui-card
entity: climate.fbh_vorlaufregelung
name: Vorlaufregelung
card_mod:
  style:
    bt-ha-control-circular-slider$: |
      g#interaction {
        display: none;
      }

```
