### ISSUE TITLE
Allow empty name for thermostat + disable kebab/mode/power

### ISSUE THREAD

**Issue by rsnodgrass** [KartoffelToby/better-thermostat-ui-card#53]
_Really like how you've cleaned up and subtly improved the default HA Thermostat card plus support for better_thermostat, thanks!_

1. This currently breaks when the name is set to empty (should just not show anything for name):

```yaml
type: custom:better-thermostat-ui-card
entity: climate.thermostat
name: ""
```

2. Would be nice to be able to hide ALL the operation modes on the thermostat for when you do not want people to control (e.g. turning heat on/off, turning thermostat off, eco mode button, etc)

```yaml
type: custom:better-thermostat-ui-card
entity: climate.thermostat
disable_heat_mode: true
disable_power: true
```

3. One further refinement would be to disable the kebab operation in top right:

```yaml
disable_kebab: true
```

In my case I'd like to leave the eco button to allow people to easily reset back to the "default" temp quickly, but hide all other modes (heat/power).

**Comment by rsnodgrass** [comment]
Btw, for those who want to accomplish not displaying the name you can accomplish this currently with a tab. However, an empty name should display similarly (but today just defaults to Thermostat).

```yaml
type: custom:better-thermostat-ui-card
entity: climate.thermostat
name: "\t"
```
