### ISSUE TITLE
Add Sensors to card

### ISSUE THREAD

**Issue by KrX3D** [KartoffelToby/better-thermostat-ui-card#94]
## What is the feature?

Hi, 
i want to add additional sensors to the card which should be shown

### Description

Till now i used the simple-thermostat card, and there i could add sensors:
```
  - type: custom:simple-thermostat
    entity: climate.kuche_000a1d8991df90
    sensors:
      - entity: sensor.kueche_temp_diff
        name: Offset
        unit: ' °C'
```

![image](https://user-images.githubusercontent.com/18599852/217380420-38937817-3889-48c6-a62e-b85ce68d6a28.png)

It would be nice if this feature would be integrated into BT, and the sensors could be added to the left side of the thermostat

EDIT: 

For now i added some chips wit mushroom card, but i dont really like that

![image](https://user-images.githubusercontent.com/18599852/217385186-e11915e7-a7dd-4dda-9f81-4f7285dbbcf6.png)
